[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
either = "1.15.0"
itertools = "0.14.0"
thiserror = "2.0.17"
static_assertions = "1.1.0"
bitvec = "1"
rayon = "1.11.0"
